### PR TITLE
Fix menu background color on Color theme

### LINKED ISSUE #815: Background color of menus in Color theme is incorrect
# 🐛 Bug Report

The background color of menus in the Color UI theme is incorrect. It should be Forest Green + White @ 15% (according to the spec as of Nov 11 2022), but instead the background color is Forest Green.

## 💻 Repro or Code Sample

Look at a menu in the Color UI

## 🤔 Expected Behavior

Should look like this:
image

## 😯 Current Behavior

Looks like this:
image

## 💁 Possible Solution

Fix the styling -- The Color UI of the tooltip faced a similar problem, so its styling could possibly used as an example.

## 🌍 Your Environment

Not environment dependent

### PR DESCRIPTION
**Pull request by mollykreis**
# Pull Request

## 🤨 Rationale

Fixes #815

## 👩‍💻 Implementation

Style the `slot` of the menu to provide a background of White@15% in the Color theme.

## 🧪 Testing

Looked at the menu in storybook.

## ✅ Checklist

- [ ] I have updated the project documentation to reflect my changes or determined no changes are needed.

### CODE REVIEW

File: packages/nimble-components/src/menu/styles.ts [hunk 1]
```diff
@@ -48,4 +57,17 @@ export const styles = css`
         padding-top: ${smallPadding};
         padding-bottom: ${smallPadding};
     }
-`;
+`.withBehaviors(
+    themeBehavior(
+        Theme.color,
+        css`
+            :host::before {
```
Comment (jattasNI) [inline packages/nimble-components/src/menu/styles.ts:64]: I dunno if the pseudoelements video we watched this week had anything to do with you coming up with this solution, but it at least helped me understand it. Cool approach! Maybe we can use pseudoelements more often when we find ourselves needing one extra element just to add borders/backgrounds to match a design spec.

**Review by jattasNI — APPROVED** [review]

File: packages/nimble-components/src/menu/styles.ts (hunk 1 above)
Comment (mollykreis) [reply packages/nimble-components/src/menu/styles.ts:64]: @rajsite actually mentioned that what could probably use `::before` and `::after` to solve some of these styling scenarios the day before we watched the video, so the timing of everything aligned to make me want to try it out.

I noticed that the combo-box & select have the same problem, so assuming we're happy with this solution, I'll post a follow-up PR to fix those components. I'm hoping we can also leverage this approach for some table styling.

Comment (jattasNI) [reply packages/nimble-components/src/menu/styles.ts:64]: If we agree on it as a pattern then it could be helpful to describe it in our [CSS Guidelines](https://github.com/ni/nimble/blob/main/packages/nimble-components/docs/css-guidelines.md). That can obviously wait for the follow up PR.

File: packages/nimble-components/src/menu/styles.ts [hunk 2]
```diff
@@ -24,14 +28,18 @@ export const styles = css`
         min-width: 168px;
         width: max-content;
         box-shadow: ${elevation2BoxShadow};
+        position: relative;
```
Comment (rajsite) [inline packages/nimble-components/src/menu/styles.ts:31]: We shouldn't set a position on the `:host`. The user needs to be able to have full control of the element's position configuration. Should only se it on children in our control.

Comment (rajsite) [reply packages/nimble-components/src/menu/styles.ts:31]: Template is pretty minimal lol. Generally not great, but maybe we can style the slot?

Comment (mollykreis) [reply packages/nimble-components/src/menu/styles.ts]: That's a great point. I updated the code to style the slot + `:host` as the 2 overlapping elements rather than needing to use `:host` and `:host::before`.

**Review by rajsite — APPROVED** [review]

File: packages/nimble-components/src/menu/styles.ts [hunk 3]
```diff
@@ -48,4 +60,13 @@ export const styles = css`
         padding-top: ${smallPadding};
         padding-bottom: ${smallPadding};
     }
-`;
+`.withBehaviors(
```
Comment (jattasNI) [inline packages/nimble-components/src/menu/styles.ts:63]: If this pattern now spans multiple controls, should we make it a dedicated theme-aware token? (I haven't looked closely at the pattern to know if that's possible.)

If we do this, we should make sure to consider the existing token `ni-nimble-section-background-color` which currently mentions that it should be used for menu backgrounds. Either we should repurpose it or change its description to distinguish it from a new token.
