### PR TITLE
Fix radio button focus ring scrolling bug

### LINKED ISSUE #1143: Radio button keyboard focus indicator doesn't scroll with control
# 🐛 Bug Report

The radio button shows a thick border when you give it tab focus but that border is positioned on the page at the component's original location and doesn't move if the component scrolls.

## 💻 Repro or Code Sample

1. Open the Angular example app in a browser window that is tall enough for the radio button to appear on screen when the page loads.
2. Tab until it has focus
3. Scroll the page

## 🤔 Expected Behavior

Thick focus ring moves with the radio button
image

## 😯 Current Behavior

Focus ring stays at the same screen location while the component scrolls away
image

## 💁 Possible Solution

The focus indicator is an `:after` pseudo element. It probably needs to be positioned differently relative to its parent.

## 🌍 Your Environment

* OS & Device: macOS
* Browser: Reproduced in Safari, Chrome, Firefox

### PR DESCRIPTION
**Pull request by m-akinc**
# Pull Request

## 🤨 Rationale

Fixes #1143

## 👩‍💻 Implementation

The ring is a pseudo-element being positioned absolutely, so that it can overlap the rest of the control. According to the docs for the `absolute` value:

> An element with `position: absolute;` is positioned relative to the nearest positioned ancestor (instead of positioned relative to the viewport, like fixed).
> However; if an absolute positioned element has no positioned ancestors, it uses the document body, and moves along with page scrolling.

It seems that our focus ring had no positioned ancestors and was being positioned relative to the document body. The scrollable area is _contained_ by the document body, so scrolling it would not change the position of the focus ring.

Note that there must have been a positioned ancestor within the scrollable area in the radio button Storybook, because that did not exhibit the odd behavior. The focus ring scrolled along with the controls.

To fix this, all we have to do is set `position: relative;` on the `.control` element which contains the focus ring pseudo-element. This will ensure the absolute positioning is always relative to `.control`.

## 🧪 Testing

Tested in Angular example app. I also tested the other controls to make sure nothing else was showing the same non-scrolling behavior.

## ✅ Checklist

- [x] I have updated the project documentation to reflect my changes or determined no changes are needed.

### CODE REVIEW

File: packages/nimble-components/src/radio/styles.ts [hunk 1]
```diff
@@ -30,6 +30,7 @@ export const styles = css`
     }
 
     .control {
+        position: relative;
```
Comment (jattasNI) [inline packages/nimble-components/src/radio/styles.ts:33]: I cringe whenever we implement a change and don't have a way to auto test it. I guess we don't auto test any of our focus states so there's precedence for this, but it's worth a quick brainstorm to see if we could come up with something to improve matters.

One idea is a unit test that queries for an element in the shadow dom that has `position: relative` set on it and fails if it's not found. At least that way, if we refactor the component and unwittingly remove this, a test will fail and we'll pause to think about why.

Thoughts?

**Review by jattasNI — COMMENTED** [review]
I manually tested in Firefox and Safari on macOS and it works great ⃝

File: packages/nimble-components/src/radio/styles.ts (hunk 1 above)
Comment (jattasNI) [reply packages/nimble-components/src/radio/styles.ts:33]: Fair enough, I'm ok to skip a test in this case. Thanks for thinking about it.

**Review by jattasNI — APPROVED** [review]

**Review by rajsite — APPROVED** [review]
