### PR TITLE
Adjust control height based on label presence

### LINKED ISSUE #480: Omitting a label on textfield keeps label height
# 🐛 Bug Report

If you don't want a label on your text field, you have to explicitly set `ni-nimble-internal-label-height` to 0px because the textfield's height is calculated using the label height and control height, regardless of whether or not a label has been configured on the control

## 🤔 Expected Behavior
If no label is configured on the textfield, its height should just be the control height.

## 😯 Current Behavior
If no label is configured on the textfield, its height is still the control height + label height.

## 💁 Possible Solution

- Adjust the textfield's height based on whether or not a label is configured on it.
- Have a way to configure the textfield (such as a css class) to not include the label height as part of its height

## 🔦 Context

See discussion on [this PR](https://ni.visualstudio.com/DevCentral/_git/Skyline/pullrequest/287078?_a=files&path=/Web/Workspaces/SystemLinkShared/projects/systemlink-lib-angular/src/sl-properties/sl-properties.component.scss&discussionId=2979042)

To have a textfield without label space, I have to set `ni-nimble-internal-label-height` to 0px

## 🌍 Your Environment

_Not environment specific_

### PR DESCRIPTION
**Pull request by m-akinc**
# Pull Request

## 🤨 Rationale

Fixes #480

## 👩‍💻 Implementation

If we no longer explicitly set the control height in the CSS of the text/number field, then the height is calculated the way that we want (i.e. 48px with a label and 32px without). I confirmed that showing the error string still doesn't affect the calculated height, which is correct.

## 🧪 Testing

Tested in Storybook

## ✅ Checklist

- [x] I have updated the project documentation to reflect my changes or determined no changes are needed.

### CODE REVIEW

File: packages/nimble-components/src/text-field/index.ts [hunk 1]
```diff
@@ -51,7 +51,9 @@ export class TextField extends FoundationTextField implements ErrorPattern {
     public override connectedCallback(): void {
         super.connectedCallback();
         if (this.textContent?.trim()) {
-            this.style.height = `calc(${labelHeight.getValueFor(this)} + ${controlHeight.getValueFor(this)})`;
+            this.style.height = `calc(${labelHeight.getValueFor(
```
Comment (rajsite) [inline packages/nimble-components/src/text-field/index.ts:54]: This is definitely not how we should be styling controls. As much as possible we need to be using CSS for layout and this is straying farther from that. I haven't tried to evaluate what is going on here but we need strong justification for going down this path that I do not see discussed in the PR.

**Review by rajsite — CHANGES_REQUESTED** [review]

File: packages/nimble-components/src/text-field/index.ts (hunk 1 above)
Comment (m-akinc) [reply packages/nimble-components/src/text-field/index.ts:54]: This was the only way I could think of. I'm not aware of any way to do this in CSS. Do you think I am missing a better approach, or do you just want me to be more explicit in the description that this is the only way I could come up with?

Comment (rajsite) [reply packages/nimble-components/src/text-field/index.ts:54]: > I'm not aware of any way to do this in CSS.

The issue description in it's possible solutions gives a CSS-based approach. Requiring an additional class or attribute is not a great solution but if you tried and eliminated CSS based solutions such as that one some context of what you tried would be useful. 

> If someone programmatically adds/removes a label after the element is added to the DOM, the element will have the wrong height. I don't think we care very much to support that scenario.

I strongly disagree with this assessment. Our controls are designed to dynamically respond to attributes / properties / slotted content, etc. I would expect responsiveness to changes in configuration inline with our other controls.

Comment (m-akinc) [reply packages/nimble-components/src/text-field/index.ts:54]: I talked with Milan and he turned me on to an approach using FAST's `slotted` directive which is already being used in the text field and number field templates. The idea is that the `slotted` directive will assign any slotted content (i.e. the label text) to a `defaultSlottedNodes` observable member. I can then write a `defaultSlottedNodesChanged()` method that sets (or removes) a `labeled` class on the `nimble-text-field` element. Then writing the CSS to have a different height based on the presence of the `labeled` class is trivial.

However, I am not seeing the `slotted` directive work the way it should. `defaultSlottedNodes` is never populated with my label text node. It is initialized to an empty array, and never changes after that.

Comment (m-akinc) [reply packages/nimble-components/src/text-field/index.ts]: It looks like a super simple approach will work. If we just stop explicitly setting the height on the text/number field, then the height ends up being calculated correctly, whether there is a label (48px) or not (32px). I tested this out in Storybook.

File: packages/nimble-components/src/number-field/styles.ts [hunk 2]
```diff
@@ -29,7 +28,6 @@ export const styles = css`
         outline: none;
         user-select: none;
         color: ${bodyFontColor};
-        height: calc(${labelHeight} + ${controlHeight});
```
Comment (atmgrifter00) [inline packages/nimble-components/src/number-field/styles.ts:32]: Would we not want to make this change more broadly? Why would this only apply to the text-field?

Comment (rajsite) [reply packages/nimble-components/src/number-field/styles.ts:32]: +1 the PR linked from the issue describes how the textarea has the same fix. Seems like it should be confirmed that we are not playing whack-a-mole

File: change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json [hunk 3]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (rajsite) [inline change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json:1]: Seems like we don't have anything in Chromatic that would help identify regressions in the control sizing. Seems like it would be useful to add chromatic tests per control that would help identify size changes with and without labels.

**Review by rajsite — CHANGES_REQUESTED** [review]

File: packages/nimble-components/src/number-field/styles.ts (hunk 2 above)
Comment (m-akinc) [reply packages/nimble-components/src/number-field/styles.ts:32]: The problem only applies to text fields and number fields. The only other control that has an optional label that is vertically stacked on the control is the text area. The text area already doesn't set an explicit height, so its height is calculated correctly whether the label is there or not.

File: change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json (hunk 3 above)
Comment (m-akinc) [reply change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json:1]: I added a Storybook test each for text field, text area, and number field. The tests stack two instances of the control vertically, one with a label, one without. I also add a dashed border to more easily see the bounds of the control.
image

**Review by rajsite — APPROVED** [review]

File: change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json [hunk 4]
```diff
@@ -0,0 +1,7 @@
...
+  "type": "patch",
```
Comment (jattasNI) [inline change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json:2]: I almost suggested deleting the `labelHeight` token since it's no longer used within Nimble but it's still used in [one place in Skyline](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Web/Workspaces/SystemLinkShared/projects/systemlink-lib-angular/src/sl-details-panel/sl-details-item-custom-property/sl-details-item-custom-property.component.scss). Probably worth a quick look at that code to see if your newfound label best practices would lead us to do it differently too.

File: change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json (hunk 3 above)
Comment (jattasNI) [inline change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json:1]: The switch and radio group also support labels. Do we expect them to behave the same way? If so, could you add tests for them too? 

If there's tech debt around those labels that makes them behave differently, no need to grow the scope of this PR and fix that now (as long as that tech debt is tracked somewhere).

**Review by jattasNI — APPROVED** [review]

**Review by atmgrifter00 — APPROVED** [review]

File: change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json [hunk 5]
```diff
@@ -0,0 +1,7 @@
...
+  "comment": "Adjust control height based on label presence",
+  "packageName": "@ni/nimble-components",
+  "email": "7282195+m-akinc@users.noreply.github.com",
+  "dependentChangeType": "patch"
+}
```
Comment (rajsite) [inline change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json:7]: As part of the bubble-up of the PR or as a follow-on, this workaround should be removed [from sl-properties](https://ni.visualstudio.com/DevCentral/_git/Skyline?path=/Web/Workspaces/SystemLinkShared/projects/systemlink-lib-angular/src/sl-properties/sl-properties.component.scss&version=GBmaster&line=36&lineEnd=37&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

File: change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json (hunk 3 above)
Comment (m-akinc) [reply change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json:1]: I've added a story for the switch and the radio group.

File: change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json (hunk 5 above)
Comment (m-akinc) [reply change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json:7]: I will remove the workaround after these changes make it into systemlink-lib-angular.

File: change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json (hunk 4 above)
Comment (m-akinc) [reply change/@ni-nimble-components-30881da7-4a97-48ad-81c0-db79e1c01c98.json:2]: I think it is worth keeping the token around in case we need to size something _other_ than a label to have the same height as a label. I've changed the documentation for the token in Storybook to say that you should not explicitly set the height of a label, but set the font instead.

I confirmed that setting the label height is unnecessary for the error label to be the proper height (16px). I will remove that use of the token in a follow-up PR -- at the same time I remove the workaround that Milan mentions in his comment.
