### PR TITLE
Fix bug with setting a title on spinner in Firefox

### LINKED ISSUE #1825: Setting title on nimble-spinner doesn't work correctly in FF
# 🐛 Bug Report

In Firefox, setting a `title` on the `nimble-spinner` doesn't work correctly. It is very difficult to get the title to appear by hovering over the spinner. It seems related to the animation because if you stop the animation, the title works correctly.

## 🤔 Expected Behavior

Hovering a `nimble-spinner` should show the `title`, if set.

## 😯 Current Behavior

Hovering a `nimble-spinner` with a `title` set doesn't show the title in Firefox.

## 💁 Possible Solution

Add an overlay element, such as a `div` over the spinner that the `title` can be set on that doesn't have animation.

## 🌍 Your Environment

Firefox 122.0.1

### PR DESCRIPTION
**Pull request by mollykreis**
# Pull Request

## 🤨 Rationale

Resolves #1825 

## 👩‍💻 Implementation

I created a transparent overlay on top of the spinning bits in the spinner's template. This is enough to get the title to display correctly in Firefox and not flicker when the bits move.

## 🧪 Testing

Manually verified that the title now displays correctly in Firefox and still displays correctly in Edge.

## ✅ Checklist

- [ ] I have updated the project documentation to reflect my changes or determined no changes are needed.

### CODE REVIEW

**Comment by mollykreis** [comment]
@msmithNI, can you buddy this PR for me?

**Review by msmithNI — APPROVED** [review]

File: packages/nimble-components/src/spinner/styles.ts [hunk 1]
```diff
@@ -19,6 +19,13 @@ export const styles = css`
         aspect-ratio: 1 / 1;
     }
 
+    div.overlay {
+        z-index: 1;
+        position: absolute;
+        height: inherit;
```
Comment (rajsite) [inline packages/nimble-components/src/spinner/styles.ts:25]: We shouldn't be configuring sizes as inherit, see: https://github.com/ni/nimble/issues/1479#issuecomment-1703313419

**Review by jattasNI — APPROVED** [review]
Validated titles work well in macOS FF (and Safari, though they worked well there already)

File: packages/nimble-components/src/spinner/styles.ts (hunk 1 above)
Comment (mollykreis) [reply packages/nimble-components/src/spinner/styles.ts]: I changed the display of the host to be `inline-grid` so that I could easily overlap the overlay and spinner container without having to use `position: absolute` and `height: inherit`.

File: packages/nimble-components/src/spinner/styles.ts [hunk 2]
```diff
@@ -12,16 +12,22 @@ import { Theme } from '../theme-provider/types';
...
-    ${display('inline-flex')}
+    ${display('inline-grid')}
 
     :host {
         height: ${spinnerSmallHeight};
         aspect-ratio: 1 / 1;
     }
 
+    div.overlay {
+        z-index: 1;
```
Comment (m-akinc) [inline packages/nimble-components/src/spinner/styles.ts:23]: Should use `ZIndexLevels.zIndex1` from `utilties/style/types.ts`.

**Review by rajsite — APPROVED** [review]
