### PR TITLE
Fix the size of the action menu within the table

### LINKED ISSUE #1145: Table action menu button should be 24x24
# 🐛 Bug Report

After a discussion with designers, we've decided that the action menu button in the table should be 24px by 24px rather than the default 32px by 32px. With this size button centered on the row, it will have some padding between the top & bottom of the row rather than being the exact same height as the row.

The one difficulty in addressing this is that the menu items should remain at the standard "controlHeight". Their height should not be affected by the size of the menu button.

## 🤔 Expected Behavior

The action menu button on a table row should be smaller than the rows. It should be 24x24 rather than 32x32.

## 😯 Current Behavior

The action menu button on a table row is the same height as the row, so there isn't any padding between the button and the top & bottom of the row.

## 💁 Possible Solution

Set `${controlHeight.cssCustomProperty}: 24px;` for the action menu in the table-cell CSS. However, there would also need to be a change to keep that new control height from also applying to the menu items within the action menu.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

### PR DESCRIPTION
**Pull request by mollykreis**
# Pull Request

## 🤨 Rationale

Resolves #1145 

## 👩‍💻 Implementation

- Update the styling of the icon button to have an aspect ratio of 1/1
- Update usages within nimble where we were resizing an icon button to only set the height
- Update the size of the action menu in the table

## 🧪 Testing

Manually tested that the button is the right size and correctly positioned.

## ✅ Checklist

- [x] I have updated the project documentation to reflect my changes or determined no changes are needed.

### CODE REVIEW

**Review by jattasNI — APPROVED** [review]

**Review by rajsite — APPROVED** [review]

File: packages/nimble-components/src/table/components/cell/styles.ts [hunk 1]
```diff
@@ -32,5 +33,8 @@ export const styles = css`
         margin-left: auto;
         flex-shrink: 0;
         flex-grow: 0;
+        width: ${controlSlimHeight};
+        height: ${controlSlimHeight};
```
Comment (rajsite) [inline packages/nimble-components/src/table/components/cell/styles.ts:37]: Ah dang it, srry molly, just remembered. Can you use this aspect-ratio pattern so we can do this more consistently (also makes it less weird to assign a height to a width)?

https://github.com/ni/nimble/blob/97d4deddb38093b51ca3916aac6cf4ccab138415/packages/nimble-components/src/spinner/styles.ts#L16-L17

Comment (rajsite) [reply packages/nimble-components/src/table/components/cell/styles.ts]: Good idea 👍

Comment (mollykreis) [reply packages/nimble-components/src/table/components/cell/styles.ts]: hmm...it seems like that change caused a styling change in safari on all of our icon buttons.

Comment (mollykreis) [reply packages/nimble-components/src/table/components/cell/styles.ts]: After some investigation, I discovered that Chromatic uses Safari 16.0 (released September 2022), and the icon button renders as 34x32 in that version of Safari rather than 32x32 as it does in the latest version of Safari.

Should we come up with a solution that renders correctly in Safari 16.0, such as not using the `aspect-ratio` styling? Or, should it be a "known issue" that the Chromatic snapshots of icon buttons are not the correct dimensions?

Comment (jattasNI) [reply packages/nimble-components/src/table/components/cell/styles.ts]: As additional input to the decision, [Chromatic has historically updated browser versions very infrequently](https://www.chromatic.com/docs/infrastructure-release-notes), roughly 1-2 times per year. The last release was February 2023 so if we opt for a "workaround" solution that's not our preferred long-term practice then it might need to remain in place for quite a while.

I waffled quite a bit but I think I'm ok with accepting the Safari diffs and calling this a "known issue" since the version that exhibits the bug is outside our 6 month support window. (Others can feel free to push for a different approach). 

If we go that direction, I can't think of a great way to track the known issue. [Chromatic auto-accepts diffs when they do an infrastructure update](https://www.chromatic.com/docs/browsers?ref=chromaticblog.ghost.io#browser-upgrades) meaning there won't be any action for us to take when it's fixed, so probably not much value in filing a bug. I vote we just accept the diffs and move on.
