### PR TITLE
Green column divider

### LINKED ISSUE #1880: Header divider doesn't turn green on hover
# 🐛 Bug Report

According to the [visual design for the table](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=5661-6994&mode=design&t=APYAPbMUE13p5LMT-0), the divider between headers should turn green on hover rather than staying gray.

## 🤔 Expected Behavior

The column divider should change color when it is hovered.

## 😯 Current Behavior

The column divider does not change color when it is hovered.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

### PR DESCRIPTION
**Pull request by mollykreis**
# Pull Request

## 🤨 Rationale

Fixes #1880 

## 👩‍💻 Implementation

- A hovered column divider is now `borderHoverColor`
- The column divider that is being dragged is styled using the `active` class to be `borderHoverColor`
- The second column divider of the column being resized (assuming it exists) is styled using the `visible` class to be visible

## 🧪 Testing

- Manually tested in storybook
- Update unit tests that check for the correct CSS classes to be applied to dividers during a drag operation

## ✅ Checklist

- [ ] I have updated the project documentation to reflect my changes or determined no changes are needed.

### CODE REVIEW

**Comment by mollykreis** [comment]
@m-akinc, will you buddy this PR for me?

File: packages/nimble-components/src/table/template.ts [hunk 1]
```diff
@@ -83,8 +83,14 @@ export const template = html<Table>`
                             ${repeat(x => x.visibleColumns, html<TableColumn, Table>`
                                 <div class="header-container">
                                     ${when((_, c) => c.index > 0, html<TableColumn, Table>`
-                                        <div class="column-divider left ${(_, c) => `${c.parent.layoutManager.activeColumnIndex === c.index ? 'active' : ''}`}" 
-                                             @mousedown="${(_, c) => c.parent.onLeftDividerMouseDown(c.event as MouseEvent, c.index)}">
+                                        <div
+                                            class="
+                                                column-divider
+                                                left
+                                                ${(_, c) => `${c.parent.layoutManager.activeColumnIndex === c.index ? 'visible' : ''}`}
```
Comment (m-akinc) [inline packages/nimble-components/src/table/template.ts:90]: So a divider can be visible without having the `visible` class, right? It looks like `visible` is only set when a divider is being dragged. That initially confused me. Could we change the class to something like `column-sizing` or `column-active`?

File: packages/nimble-components/src/table/styles.ts [hunk 2]
```diff
@@ -117,6 +118,25 @@ export const styles = css`
...
+        display: block;
+        z-index: ${ZIndexLevels.zIndex1};
+    }
+
+    .column-divider.active {
+        border-color: ${borderHoverColor};
+    }
+
+    .header-container:hover .column-divider.left,
+    .header-container:hover .column-divider.right {
```
Comment (m-akinc) [inline packages/nimble-components/src/table/styles.ts:135]: Can't `left` and `right` be omitted?:
```suggestion
    .header-container:hover .column-divider {
```

File: packages/nimble-components/src/table/styles.ts [hunk 3]
```diff
@@ -117,6 +118,25 @@ export const styles = css`
         position: absolute;
     }
 
+    .column-divider:hover {
+        border-color: ${borderHoverColor};
+    }
+
+    .column-divider.visible {
+        display: block;
+        z-index: ${ZIndexLevels.zIndex1};
```
Comment (m-akinc) [inline packages/nimble-components/src/table/styles.ts:127]: Maybe `z-index` should just go in the base `.column-divider` styling, so it doesn't have to be set in two places.

File: packages/nimble-components/src/table/styles.ts [hunk 4]
```diff
@@ -117,6 +118,25 @@ export const styles = css`
         position: absolute;
     }
 
+    .column-divider:hover {
```
Comment (m-akinc) [inline packages/nimble-components/src/table/styles.ts:121]: Any reason not to combine the selectors to avoid duplicating the styles? I.e.
```css
.column-divider:hover,
.column-divider.active { ... }

.column-divider.visible,
.header-container:hover .column-divider { ... }
```

**Review by m-akinc — APPROVED** [review]

File: packages/nimble-components/src/table/styles.ts (hunk 2 above)
Comment (mollykreis) [reply packages/nimble-components/src/table/styles.ts:135]: Yes, it seems like they can be omitted. I'm not sure why the styling wasn't originally written that way.

File: packages/nimble-components/src/table/template.ts (hunk 1 above)
Comment (mollykreis) [reply packages/nimble-components/src/table/template.ts:90]: That's a good point. I've updated the two classes to be `column-active` and `divider-active`.

File: packages/nimble-components/src/table/styles.ts [hunk 5]
```diff
@@ -115,6 +116,18 @@ export const styles = css`
...
+        z-index: ${ZIndexLevels.zIndex1};
+    }
+
+    .column-divider:hover,
+    .column-divider.divider-active {
+        border-color: ${borderHoverColor};
+    }
+
+    .column-divider.column-active,
+    .header-container:hover .column-divider,
```
[the remark this answers is not in the document]
Comment (mollykreis) [reply packages/nimble-components/src/table/styles.ts:128]: ah...yes

**Review by rajsite — APPROVED** [review]

**Review by jattasNI — APPROVED** [review]

**Comment by rajsite** [comment]
@mollykreis unmarking auutomerge to get the renoovate PRs through, will re-enable after
