### PR TITLE
Fix tab keyboard focus style

### LINKED ISSUE #949: Tab styling is off from design spec
# 🐛 Bug Report
Current tab styling for the selected state does not match the visual design. The upper, 1px line should be narrower than the bottom line. It is currently that same width

Current implementation:
image

Visual design:
image

Related PRs:
- #948

### PR DESCRIPTION
**Pull request by m-akinc**
# Pull Request

## 🤨 Rationale

Fixes #949.

The keyboard focused styling of the tab did not exactly match the design spec. Specifically, the extra thin line above the thicker selection line extended all the way to the edge of the tab instead of being 3px short on each side.

## 👩‍💻 Implementation

Changed the CSS width to subtract the 6 pixels.

## 🧪 Testing

Storybook

## ✅ Checklist

- [x] I have updated the project documentation to reflect my changes or determined no changes are needed.

### CODE REVIEW

File: packages/nimble-components/src/tab/styles.ts [hunk 1]
```diff
@@ -84,7 +84,7 @@ export const styles = css`
     }
 
     :host(${focusVisible})::before {
-        width: 100%;
+        width: calc(100% - 6px);
```
Comment (rajsite) [inline packages/nimble-components/src/tab/styles.ts:87]: Can you make a private prop for this magic number? Maybe something like `--ni-private-focus-indicator-inset-width` or something?

**Review by rajsite — APPROVED** [review]

**Review by jattasNI — APPROVED** [review]

**Comment by jattasNI** [comment]
I modified the PR description to include a link that will close the related issue (which was created after this PR was created, so no judgment for not linking it yourself!). Just wanted to mention it in case there is more work to do before we can close the issue.
